baseURL = "https://mikegraf.me/"
languageCode = "en-us"
title = "mikegraf.me"
theme = "nix"


### Below are nix theme options
[params]
GithubID = "maerf0x0"
LinkedInID = "mikegraf"
Email = "mikegraf000@gmail.com"
Name = "Mike Graf"
ProfilePicture = "https://scontent-sjc3-1.xx.fbcdn.net/v/t1.0-9/24296402_1750714308567319_70150464812498180_n.jpg?_nc_cat=0&oh=f6440f6ebb84b152c10fa2ae2ca23a4a&oe=5BDC6883"
HeaderUsername = "maerf0x0"
HeaderHostname = "::1"
About = "I'm a software engineer with interests in building APIs, statically typed languages, and building performant data pipelines."
#   GnuPGFingerprint = "your_gpg_fingerprint"
#   StackExchangeID = "your_stackexchange_id"
#   StackOverflowID = "your_stackoverflow_id"
#   GitlabId = "your_gitlab"
#   BitbucketID = "your_bitbucket_id"
#   TwitterID = "your_twitter"
#   CodepenID = "your_codepen"
#   GoogleplusID = "your_googleplus"
#   FacebookID = "your_facebook"
#   InstagramID = "your_instagram"
#   TelegramID = "your_telegram"
#   Phone = "+1-201-555-0123"
#   Mobile = "+1-201-555-0123"
#   GoogleAnalytics = "your_google_analytics_id"
#   SlackURL = "https://join.slack.com/..."
#   PayPalMeID = "https://www.paypal.me/..."
#   XingURL = "https://www.xing.com/profile/..."
#   CvURL = "your_cv_url"

#  To add a menu item add [[menu.header]] item to config.toml. For example:
#
#  [menu]
#    [[menu.header]]
#      name = "posts"
#      weight = 0
#      url = "/posts"
#  To add a submenu item add [[menu.header]] item with a parent parameter to config.toml. For example:
#
#  [menu]
#    [[menu.header]]
#      identifier = "post"
#      name = "posts"
#      weight = 0
#      url = "/post"
#    [[menu.header]]
#      parent = "post"
#      name = "All Posts"
#      url = "/post"
#    [[menu.header]]
#      parent = "post"
#      name = "categories"
#      url = "/categories"
#    [[menu.header]]
#      parent = "post"
#      name = "tags"
#      url = "/tags"
#  To enable disqus comments add disqusShortname to your config.toml.
#
#  You can turn off disqus comments per page by adding nocomments = true to the front matter.
